[versions]
ktor = "2.0.0"
coroutines = "1.6.4"
compose = "1.4.1"
compose-compiler = "1.4.5"
accompanist = "0.31.0-alpha"
sqldelight = "1.5.5"
arrow = "1.1.5"

[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common" }
compose-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
android-test-orchestrator = { module = "androidx.test:orchestrator", version = "1.4.2" }
turbine = { module = "app.cash.turbine:turbine", version = "0.12.3" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
stdlib-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-headers = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor-server-logging-jvm = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktor-server-tests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor" }
ktor-client-mock-jvm = { module = "io.ktor:ktor-client-mock-jvm", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.7.0" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.4.1" }
settings-core = { module = "com.russhwolf:multiplatform-settings-no-arg", version = "1.0.0" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flow-layout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }
desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.3" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
logging = { module = "ch.qos.logback:logback-classic", version = "1.4.0" }
collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }
coil = { module = "io.coil-kt:coil-compose", version = "2.3.0" }
compose-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version = "1.4.1" }
splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0" }

[bundles]
ktor-server = ["ktor-server-core", "ktor-server-netty", "ktor-server-websockets", "ktor-server-headers", "ktor-server-logging-jvm"]
compose = [
    "compose-ui",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material",
    "compose-icons",
    "compose-runtime",
    "compose-animation",
    "compose-activity",
    "compose-tooling-preview",
]
accompanist = [
    "accompanist-swiperefresh",
    "accompanist-flow-layout"
]

[plugins]
