# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'shared_app_lib', :path => '../shared-app-lib'
 # pod 'tea_core', :path => '../tea-core'
  #pod 'Alamofire', '4.9.1'
  
  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosAppUITests' do
    # Pods for testing
  end

end
