name: Tea Bag CI Workflow

on: [ push, pull_request ]

jobs:

  Check:
    env:
      DEFAULT_BRANCH: master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 19
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run static code analysis
        run: ./gradlew detekt --no-configuration-cache

  Android-emulator-tests:
    env:
      DEFAULT_BRANCH: master
    needs: Check
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 19
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run connected Android tests
        run: ./gradlew samples:app:pixel6api34DefaultDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" --no-configuration-cache

  IOS-app-build:
    env:
      DEFAULT_BRANCH: master
    needs: Check
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 19
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build IOS app
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: samples/iosApp/iosApp.xcworkspace
          scheme: iosApp
          destination: 'platform=iOS Simulator,name=iPhone 15'
          configuration: Debug
          action: build

  Unit-tests:
    env:
      DEFAULT_BRANCH: master
    needs: Check
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 19
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew check -x detekt --no-configuration-cache
      - name: Archive test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: tests-report
          path: build/junit-reports/**

  Deploy:
    env:
      DEFAULT_BRANCH: master
    needs: [Unit-tests, Android-emulator-tests, IOS-app-build]
    runs-on: macos-14
    # tags should be of the form:
    # <no-value> -> dev build
    # v1.2.3-alpha1 -> alpha build
    # v1.2.3-rc1 or v1.2.3-alpha4-rc5 -> alpha RC
    # v1.2.3 -> stable
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 19
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish artifacts
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository publishPlugin copyArtifacts --no-configure-on-demand --no-configuration-cache
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          PUBLISH_PLUGIN_TOKEN: ${{ secrets.PUBLISH_PLUGIN_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish-artifacts
          path: build/artifacts/**