name: Tea Bag CI Workflow

on: [ push, pull_request ]

jobs:

  Check:
    env:
      DEFAULT_BRANCH: master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run static code analysis
        run: ./gradlew detektAll

  Android-emulator-tests:
    env:
      DEFAULT_BRANCH: master
    needs: Check
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run connected Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          script: ./gradlew samples:app:connectedCheck

  Ios-tests:
    env:
      DEFAULT_BRANCH: master
    needs: Check
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build IOS app
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: samples/iosApp/iosApp.xcworkspace
          scheme: iosApp
          destination: 'platform=iOS Simulator,name=iPhone 12 Pro'
          configuration: Debug
          action: build

  Unit-tests:
    env:
      DEFAULT_BRANCH: master
    needs: Check
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew check -x detekt
      - name: Archive test reports
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: tests-report
          path: build/junit-reports/**

  Deploy:
    env:
      DEFAULT_BRANCH: master
    needs: [Unit-tests, Android-emulator-tests, Ios-tests]
    runs-on: macos-11
    # tags should be of the form:
    # <no-value> -> dev build
    # v1.2.3-alpha1 -> alpha build
    # v1.2.3-rc1 or v1.2.3-alpha4-rc5 -> alpha RC
    # v1.2.3 -> stable
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/develop'
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish artifacts
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository publishPlugin copyArtifacts --no-configure-on-demand
        env:
          GITHUB_TAG: ${{ steps.get_version.outputs.GITHUB_TAG }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          PUBLISH_PLUGIN_TOKEN: ${{ secrets.PUBLISH_PLUGIN_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish-artifacts
          path: build/artifacts/**